### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by chovy** [piotrmurach/coinpare#1]
I did `gem install coinpare` but when I run `coinpare` I get command not found.

I'm using zsh.

**Comment by piotrmurach** [comment]
Hi Anthony 👋 

Thanks for giving `coinpare` a try. I run a container build from based Ruby `2.7` image with `coinpare` gem installed:

```
FROM ruby:2.7
RUN ["gem", "install", "coinpare"]
```

The `coinpare` command executes fine inside the cointainer. The default location is `/usr/local/bundle/bin/coinapre`. 

I'm not sure how you installed your Ruby but it seems that your installation is giving you a problem. You can follow [rbenv installation guides](https://github.com/rbenv/rbenv#installation) to manage your Rubies.

**Comment by chovy** [comment]
i had to add some gem stuff to my environment. 

```
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
export EDITOR=vim
```

**Comment by piotrmurach** [comment]
@chovy Glad this fixed it for you, though I must admit I've never needed to add gem install binaries to my path as this should be handled automatically. For example, `rbenv` handles this via its shims. Curious to know how do you install your Ruby?

**Comment by chovy** [comment]
i used `pacman -S ruby` on arch

**Comment by piotrmurach** [comment]
Thanks. Ah, apparently, Arch by default doesn't install gems system-wide but per user to prevent conflicts with `pacman` installed gems. So to execute a binary, you need to either provide a full path `~/.gem/ruby/bin/coinpare` or tweak your `$PATH` env var. This will help to answer queries in the future when someone uses Arch linux.
