### ISSUE TITLE
how to finish adding a coin?

### ISSUE THREAD

**Issue by ralyodio** [piotrmurach/coinpare#3]
If I do ctrl-c it kills it.

i have to add a dummy coin and then say "no". how else can i say i'm done editing?

**Comment by piotrmurach** [comment]
I assume you're creating a new portfolio. You're asked whether you want to add a coin or not, each time you enter a new coin. If you don't want to add any more coins answer `no` at the prompt. There is no way to stop adding a coin mid-way once you decided suddenly for some reason that you no longer want to add a given coin. There are commands for removing coins as well as editing the holdings file in your editor once you're done adding. As far as the `ctrl-c` behaviour goes, I believe it acts as expected from any Unix tool, it interrupts a program. I'd like to hear your suggestions on how to improve this and would welcome a PR.
